 - name: Deploy Cecil
   hosts: '{{ HOSTSCOPE }}'
  # hosts: '{{ HOSTSCOPE }}'
   become: yes

   tasks:

   - name: Create Cecil Directory
     ansible.builtin.file:
       path: /opt/cecil
       state: directory
       mode: '0755'

   - name: Copy Cecil contents to remote server
     ansible.builtin.copy:
       src: /cecil/
       dest: /opt/cecil/
       owner: '{{ USERNAME }}'
       group: '{{ USERNAME }}'
       mode: '0755'

   - name: Update apt cache and make pip is installed
     apt:
       name: python3-pip
       update_cache: yes

   - name: Install configparser python package
     ansible.builtin.pip:
       name: configparser

   - name: Install requests python package
     ansible.builtin.pip:
       name: requests

   - name: Install regex python package
     ansible.builtin.pip:
       name: regex

   - name: Install psutil python package
     ansible.builtin.pip:
       name: psutil

   - name: Install argparse python package
     ansible.builtin.pip:
       name: argparse

   - name: Install typing python package
     ansible.builtin.pip:
       name: typing

   - name: Install docker python package
     ansible.builtin.pip:
       name: docker

   - name: Install lib-platform python package
     ansible.builtin.pip:
       name: lib-platform

   - name: Install yaml python package
     ansible.builtin.pip:
       name: pyyaml