version: '3'
services:
  cecil:
    image: madeofpendletonwool/cecil:latest
    container_name: cecil
    tty: true
    environment:
      # ID and Secret for Github Authentication

      - CLIENT_ID={{ Github_ClientID }}
      - CLIENT_SECRET={{ Github_Secret }}
      - CONFIG_PATH=${CONFIG_PATH}
      # The auth URL is the url that you are using to connect to the app. This is required so the auth token is directed to the right location. Use the url that you use for cecil plus '/api/oauth/redirect' at the end. 
      - AUTH_URL=${AUTH_URL}
      # The encryption key for password and secure data storage. We store this here because it's intended to be an environment variable. The key should be fernet compatible and you should generate it. Here's an example of how to do it.
      # Start python
      # Install Fernet if it isn't already
      #   pip install fernet
      # Import it
      #   from cryptography.fernet import Fernet
      # Generate the key
      #   print(Fernet.generate_key())
      # Drop the output key indo the encryption_key var below
      - ENCRYPTION_KEY=${ENCRYPTION_KEY=${AUTH_URL}
    ports:
      - 38355:38355
    volumes:
      - ~/cecil/config:/opt/cecil
    restart: always