version: '3'
services:
  cecil:
    image: madeofpendletonwool/cecil:main
    container_name: cecil
    env_file: env_file
    tty: true
    ports:
      - 38355:38355
    volumes:
      - /home/collinp/cecil2:/opt/cecil
    restart: always

